# File: .github/workflows/deploy.yml
name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      # -------------------
      # Backend: Build & Deploy
      # -------------------
      - name: Build & Push backend Docker image
        working-directory: backend
        shell: pwsh
        run: |
          docker build -t "gcr.io/$($env:GCP_PROJECT_ID)/social-media-backend:$($env:GITHUB_SHA)" .
          echo $env:GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io
          docker push "gcr.io/$($env:GCP_PROJECT_ID)/social-media-backend:$($env:GITHUB_SHA)"

      - name: Deploy backend to Cloud Run
        shell: pwsh
        run: |
          gcloud run deploy social-media-backend `
            --image "gcr.io/$($env:GCP_PROJECT_ID)/social-media-backend:$($env:GITHUB_SHA)" `
            --region $($env:GCP_REGION) `
            --platform managed `
            --allow-unauthenticated `
            --set-env-vars "DB_HOST=$($env:DB_HOST),DB_USER=$($env:DB_USER),DB_PASSWORD=$($env:DB_PASSWORD),DB_NAME=$($env:DB_NAME),JWT_SECRET=$($env:JWT_SECRET)"

      - name: Get backend URL
        id: get-backend-url
        shell: pwsh
        run: |
          $BACKEND_URL = gcloud run services describe social-media-backend `
            --region $env:GCP_REGION `
            --platform managed `
            --format="value(status.url)"
          echo "BACKEND_URL=$BACKEND_URL" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Write-Host "Backend URL: $BACKEND_URL"

      # -------------------
      # Frontend: Build & Deploy
      # -------------------
      - name: Build & Push frontend Docker image
        working-directory: frontend
        shell: pwsh
        run: |
          docker build -t "gcr.io/$($env:GCP_PROJECT_ID)/social-media-frontend:$($env:GITHUB_SHA)" .
          echo $env:GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io
          docker push "gcr.io/$($env:GCP_PROJECT_ID)/social-media-frontend:$($env:GITHUB_SHA)"

      - name: Deploy frontend to Cloud Run
        shell: pwsh
        run: |
          gcloud run deploy social-media-frontend `
            --image "gcr.io/$($env:GCP_PROJECT_ID)/social-media-frontend:$($env:GITHUB_SHA)" `
            --region $env:GCP_REGION `
            --platform managed `
            --allow-unauthenticated `
            --set-env-vars "REACT_APP_API_BASE_URL=$env:BACKEND_URL"
